-- MySQL Script generated by MySQL Workbench
-- Wed Jul 10 17:31:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema modelatgebbddfinal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema modelatgebbddfinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `modelatgebbddfinal` DEFAULT CHARACTER SET utf8 ;
USE `modelatgebbddfinal` ;

-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`clients` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`clients` (
  `idClients` INT(11) NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL DEFAULT NULL,
  `Cognom` VARCHAR(45) NULL DEFAULT NULL,
  `adreça` VARCHAR(45) NULL DEFAULT NULL,
  `ciutat` VARCHAR(45) NULL DEFAULT NULL,
  `codipostal` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `recomanacio` VARCHAR(45) NULL DEFAULT NULL,
  `dataregistre` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`marcas` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`marcas` (
  `idMarcas` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idMarcas`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`proveedors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`proveedors` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`proveedors` (
  `idProveedors` INT(11) NOT NULL AUTO_INCREMENT,
  `carrer` VARCHAR(45) NULL DEFAULT NULL,
  `numero` INT(11) NULL DEFAULT NULL,
  `pis` INT(11) NULL DEFAULT NULL,
  `porta` VARCHAR(45) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `codiPostal` INT(11) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `telefon` INT(11) NULL DEFAULT NULL,
  `fax` INT(11) NULL DEFAULT NULL,
  `NIF` VARCHAR(45) NULL DEFAULT NULL,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedors`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`compras` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`compras` (
  `idCompras` INT(11) NOT NULL AUTO_INCREMENT,
  `Proveedors_idProveedors` INT(11) NOT NULL,
  `Marcas_idMarcas` INT(11) NOT NULL,
  PRIMARY KEY (`idCompras`),
  INDEX `fk_Compras_Proveedors1_idx` (`Proveedors_idProveedors` ASC),
  INDEX `fk_Compras_Marcas1_idx` (`Marcas_idMarcas` ASC),
  CONSTRAINT `fk_Compras_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `modelatgebbddfinal`.`marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compras_Proveedors1`
    FOREIGN KEY (`Proveedors_idProveedors`)
    REFERENCES `modelatgebbddfinal`.`proveedors` (`idProveedors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`empleats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`empleats` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`empleats` (
  `idEmpleats` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idEmpleats`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`monturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`monturas` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`monturas` (
  `idMonturas` INT(11) NOT NULL AUTO_INCREMENT,
  `tipu` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idMonturas`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`ulleres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`ulleres` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`ulleres` (
  `idUlleres` INT(11) NOT NULL AUTO_INCREMENT,
  `Marcas_idMarcas` INT(11) NOT NULL,
  `graduacionI` DECIMAL(5,0) NULL DEFAULT NULL,
  `graduacionD` DECIMAL(5,0) NULL DEFAULT NULL,
  `colorMontura` VARCHAR(45) NULL DEFAULT NULL,
  `colorVidrioI` VARCHAR(45) NULL DEFAULT NULL,
  `colorVidrioD` VARCHAR(45) NULL DEFAULT NULL,
  `preu` DECIMAL(10,0) NULL DEFAULT NULL,
  `Monturas_idMonturas` INT(11) NOT NULL,
  PRIMARY KEY (`idUlleres`),
  INDEX `fk_Ulleres_Marcas1_idx` (`Marcas_idMarcas` ASC),
  INDEX `fk_Ulleres_Monturas1_idx` (`Monturas_idMonturas` ASC),
  CONSTRAINT `fk_Ulleres_Marcas1`
    FOREIGN KEY (`Marcas_idMarcas`)
    REFERENCES `modelatgebbddfinal`.`marcas` (`idMarcas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ulleres_Monturas1`
    FOREIGN KEY (`Monturas_idMonturas`)
    REFERENCES `modelatgebbddfinal`.`monturas` (`idMonturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelatgebbddfinal`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modelatgebbddfinal`.`ventas` ;

CREATE TABLE IF NOT EXISTS `modelatgebbddfinal`.`ventas` (
  `idVentas` INT(11) NOT NULL AUTO_INCREMENT,
  `Empleats_idEmpleats` INT(11) NOT NULL,
  `Ulleres_idUlleres` INT(11) NOT NULL,
  `Clients_idclients` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `fk_Ventas_Empleats_idx` (`Empleats_idEmpleats` ASC),
  INDEX `fk_Ventas_Ulleres1_idx` (`Ulleres_idUlleres` ASC),
  CONSTRAINT `fk_Clients_idclient`
    FOREIGN KEY (`idVentas`)
    REFERENCES `modelatgebbddfinal`.`clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Empleats`
    FOREIGN KEY (`Empleats_idEmpleats`)
    REFERENCES `modelatgebbddfinal`.`empleats` (`idEmpleats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Ulleres1`
    FOREIGN KEY (`Ulleres_idUlleres`)
    REFERENCES `modelatgebbddfinal`.`ulleres` (`idUlleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
